version: '3.9'

services:
  frontend:
    image: nginx
    ports:
      - 3001:80
    volumes:
      - ./frontend/:/usr/share/nginx/html

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./.docker/dev.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./backend/src/
        target: /app/src/
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
